name = "SMASH"
uuid = "2871a404-2092-4ff8-a551-ec1ef3166d76"
authors = ["Jarvist Moore Frost"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
